apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rea-web
spec:
  ports:
    - port: 80
      targetPort: 9292
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Release.Name }}-rea-web