apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reaweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reaweb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reaweb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.testBox.image.repository }}:{{ .Values.testBox.image.tag }}"
        imagePullPolicy: {{ .Values.testBox.image.pullPolicy }}
        name: reaweb
        ports:
        - containerPort: 9292