{{- if .Values.testBox.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-testbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-testbox
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-testbox
    spec:
      containers:
      - name: testbox
        image: "{{ .Values.testBox.image.repository }}:{{ .Values.testBox.image.tag }}"
        imagePullPolicy: {{ .Values.testBox.image.pullPolicy }}
        command: ["/bin/bash"]    # required to stop early exit
        stdin: true               # required to stop early exit
{{- end -}}