# More details on:
# https://github.com/helm/charts/blob/master/incubator/aws-alb-ingress-controller/values.yaml
albcontroller:
  clusterName: "reaCluster"
  autoDiscoverAwsRegion: true
  autoDiscoverAwsVpcID: true

  scope:
    ingressClass: alb
    # singleNamespace: true
    # watchNamespace: "kube-system-ingress"

  podAnnotations:
    iam.amazonaws.com/role: alb-ingress-controller
  podLabels: {}
  # whether configure readinessProbe on controller pod
  enableReadinessProbe: false
  # How often (in seconds) to check controller readiness
  readinessProbeInterval: 60
  # How long to wait before timeout (in seconds) when checking controller readiness
  readinessProbeTimeout: 3
  # How long to wait (in seconds) before checking the readiness probe
  readinessProbeInitialDelay: 30
  # whether configure livenessProbe on controller pod
  enableLivenessProbe: false
  # How long to wait (in seconds) before checking the liveness probe
  livenessProbeInitialDelay: 30
  rbac:
    create: true
    serviceAccountName: alb-ingress

externaldns:
  enabled: true
  sources:
    - service
    - ingress
  provider: aws
  domainFilters:
    # List of the domains that external-dns has to watch, Route 53 should be prepared before setting this up
    - reaapp.codingchallenge.com.au
  policy: sync
  rbac:
    create: true