

apiVersion: v1
clusters:
- cluster:
    server: https://2D30D8147A49D247F6EFEDA38207ED51.yl4.ap-southeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EWXhPREE1TURFek5Wb1hEVE13TURZeE5qQTVNREV6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkFGCjBMM3M2cmIxdEUydUZMdFFEd1JIeWVQQzVkbXR4NXYxVHY4L1NCT1djbW43b1NzSmYxRXpVWFV4by9Ncmw2OWMKV2ZlVDhLbVpTaGkvd1hkN1NsZmtnK2ZoMGdjc0V5L0w2d3JYRjJTU0Q2SDZyK0g5OVNpaGkxK1hBN21EVGFKUAozK2JPdjhMSGxwQ01NL3pkTlNha0FsbkhSOTF1U2hIREF0RGowM3VheTEzbGZZYkdUUGxSOVBpNFBIK1d2TTNvCjNZWlpQc1BUUmg5YUFMUS9UYTlwNDZGbktLMFFWSURFYzBsalRyZVVGVTNEbGh3NTVJbU85YTZ0VTE0bFVCaWkKeGxMSSs3ODgvZjRvTXZGbDRSbmc4d3RKcmRjUHgyWVZRUmRRQUVSYjJsZ3BkR0FhZjRlNHRzT09ldTl3eFBGcQppQUtUaHNyOXE1N3Yybjh1QkNFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDTE1ZQWhGYlQ3aFl6OVo4a0tPM3JrYnYzNWYKc05sT2NoS2VtRGcrQVN5a3ZUUUlxRW1Ua08xT2tkZ3NRNXpvQXlCZ2k4bzVmVnQ1OGg3eUV4Sjg5NThLK3FVcwpnUGs0aU9ncnlwS2Z0SW4xYmsxbTZsWUFEZlhoS1lidUxVbDJ5ZnJrZFNET3NnUmVjaFlXMzFjZ3FSZmNIalpVCjczZmNCRy9Td2ozb0ZzblcvMVpqTTBYK29UeXc5NEpYbU40czFkZFlQYUwyY01Db0FQUUFlczhUN3JhdEZwa2MKcC8vSWdpazduV3BaZDVZWGlmSmtOdjYzYy9PL0NrNWZPazE2TmU2WmFMTlYxdlduTDNudmNMdnZKQnBSV1hiRgpzNFk4Ynk1cjNEWjhIQ0hRVUQ5WFNNaE5uR2pCanJRQktKdHpEMkxPRjJUN2czS0lqWjc0bmJjQzFKYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "reaCluster"

